# Generated by Django 5.0.1 on 2024-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=35)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('pet_adopt', models.CharField(max_length=20)),
                ('info_additional', models.TextField()),
            ],
        ),
    ]
